sudo: required
services:
  - docker

before_install:
  - docker build -t nate54o/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true nate54o/react-test npm test --

after_success:
  - docker build -t nate54o/multi-client ./client
  - docker build -t nate54o/multi-nginx ./nginx
  - docker build -t nate54o/multi-server ./server
  - docker build -t nate54o/multi-worker ./worker
  # Log into Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to Dockerhub
  - docker push nate54o/multi-client
  - docker push nate54o/multi-nginx
  - docker push nate54o/multi-server
  - docker push nate54o/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-west-1'
  app: 'multi-docker'
  env: 'Multidocker-env'
  bucket_name: 'elasticbeanstalk-us-west-1-329048240760'
  bucket_path: 'multi-docker'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY